In [1]:
import pandas as pd
import geopandas as gpd
from pathlib import Path
import geojson

In [2]:
# betrekkingslijnen Bovebrijn-Waal Pkan-Nrijn-Lek IJssel (From Remi)
# Betrekkingslijnen Rijn_versie_2018_mei_2019-def_20052019.pdf
data = Path('~/data/vaarwegen/Betrekkingslijnen2018/Betrekkingslijnen_2018_h-Lobith_650-1780_rkm.xlsx')

# betrekkingslijnen Maas
# betrekkingslijnen_maas_2019_2020.pdf
data_maas = Path('~/data/vaarwegen/KenmerkendeWaardenMaas/betrekkingslijnen_maas_2019_2020.xlsx')

# https://geodata.nationaalgeoregister.nl/nwbvaarwegen/wfs?request=GetFeature&service=WFS&version=2.0.0&outputFormat=json&typeNames=nwbvaarwegen:kmmarkeringen
kmmarkering = Path('~/data/vaarwegen/kilometerraaien/kmmarkeringen.geojson').expanduser()

# https://geodata.nationaalgeoregister.nl/nwbvaarwegen/wfs?request=GetFeature&service=WFS&version=1.1.0&outputFormat=json&typeName=vaarwegvakken
vaarwegvakken = Path('~/data/vaarwegen/kilometerraaien/vaarwegvakken.geojson').expanduser()

# Excel sheet names with corresponding vaarwegvakken names
sheet_names = {
    "Bovenrijn-Waal": "Boven-Rijn|Waal",
    "Pkan-NRijn-Lek": "Pannerdensch Kanaal|Neder-Rijn|Lek",
    "IJssel": "IJssel"
}

In [3]:
# Read betrekingslijnen  NOTE: usecols is hardcoded!
df = pd.read_excel(data, sheet_name=list(sheet_names.keys()), skiprows=[0, 1, 3, 4, 5], header=0, usecols="B:DL", index_col=0)

df_maas = pd.read_excel(data_maas, skiprows=[0, 1, 2, 3, 5, 6, 7], header=0, usecols="C:T", index_col=0)

# Add reference location discharge
for data in df:
    print(data)
    df[data]['reference_location'] = 'Lobith'
    
df_maas['reference_location'] = 'St. Pieter'

Bovenrijn-Waal
Pkan-NRijn-Lek
IJssel

In [4]:
df_maas

,80,155,280,530,1030,1280,1500,1982,2308,2609,2781,2969,3226,3578,3862,4113,4396,reference_location
2.56,44.2,44.38,44.72,45.42,46.65,47.21,47.72,48.81,49.48,50.01,50.28,50.54,50.84,51.18,51.42,51.61,51.80,St. Pieter
3.00,44.17,44.28,44.54,45.19,46.37,46.94,47.44,48.54,49.21,49.73,49.99,50.25,50.57,50.97,51.27,51.49,51.71,St. Pieter
4.00,44.17,44.27,44.48,45.03,46.09,46.59,47.01,48.03,48.65,49.13,49.36,49.58,49.85,50.18,50.47,50.71,50.96,St. Pieter
5.00,44.15,44.21,44.33,44.72,45.73,46.20,46.60,47.71,48.33,48.79,49.02,49.23,49.48,49.77,50.01,50.22,50.45,St. Pieter
6.00,44.15,44.19,44.27,44.59,45.54,46.01,46.41,47.55,48.16,48.61,48.84,49.05,49.30,49.61,49.87,50.09,50.32,St. Pieter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244.00,0.37,0.44,0.56,0.88,1.19,1.27,1.36,1.68,1.97,2.27,2.45,2.65,2.91,3.24,3.46,3.60,3.72,St. Pieter
245.00,0.36,0.44,0.56,0.86,1.17,1.24,1.32,1.61,1.88,2.17,2.35,2.55,2.81,3.16,3.38,3.52,3.64,St. Pieter
246.00,0.36,0.43,0.56,0.85,1.16,1.22,1.29,1.55,1.80,2.07,2.23,2.42,2.67,3.02,3.25,3.39,3.51,St. Pieter
247.00,0.36,0.43,0.55,0.84,1.14,1.20,1.25,1.48,1.71,1.96,2.11,2.28,2.52,2.85,3.06,3.19,3.31,St. Pieter
247.60,0.36,0.43,0.55,0.83,1.13,1.19,1.23,1.44,1.65,1.89,2.03,2.19,2.41,2.73,2.93,3.06,3.17,St. Pieter

In [5]:
# Column: Discharge Lobith [m3/s]
# Row: Kilometermarkering
# Cell: ws -> waterstand [m+NAP]

df['IJssel']

,703.3,738.98,774.78,810.84,847.19,883.69,919.63,958.35,999.8,1040.45,...,13366.1,13691.69,14023.47,14361.35,14705.3,15055.23,15411.12,15772.93,16140.64,reference_location
878.460,6.077600,6.169158,6.264063,6.349100,6.435987,6.524606,6.614836,6.706560,6.799658,6.894011,...,14.189618,14.264858,14.340961,14.417999,14.496046,14.575175,14.655464,14.736990,14.819835,Lobith
879.000,6.010000,6.100000,6.190000,6.280000,6.370000,6.450000,6.530000,6.630000,6.720000,6.810000,...,13.950000,14.010000,14.080000,14.140000,14.210000,14.280000,14.340000,14.410000,14.480000,Lobith
880.000,5.860000,5.950000,6.040000,6.120000,6.210000,6.300000,6.400000,6.490000,6.580000,6.670000,...,13.670000,13.720000,13.770000,13.820000,13.870000,13.920000,13.960000,14.010000,14.050000,Lobith
881.000,5.740000,5.820000,5.910000,6.000000,6.090000,6.180000,6.270000,6.360000,6.450000,6.540000,...,13.520000,13.560000,13.610000,13.650000,13.690000,13.730000,13.770000,13.800000,13.840000,Lobith
881.075,5.730232,5.817254,5.904985,5.993425,6.082573,6.172431,6.262998,6.354274,6.446259,6.538953,...,13.507663,13.553375,13.597475,13.639890,13.680543,13.719356,13.756249,13.791138,13.823940,Lobith
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1002.000,-0.390000,-0.390000,-0.390000,-0.390000,-0.400000,-0.390000,-0.390000,-0.380000,-0.370000,-0.370000,...,0.750000,0.790000,0.820000,0.860000,0.900000,0.940000,0.980000,1.030000,1.070000,Lobith
1003.000,-0.390000,-0.390000,-0.390000,-0.390000,-0.400000,-0.390000,-0.390000,-0.380000,-0.370000,-0.370000,...,0.680000,0.710000,0.750000,0.790000,0.830000,0.860000,0.900000,0.950000,0.990000,Lobith
1004.000,-0.390000,-0.390000,-0.390000,-0.390000,-0.400000,-0.390000,-0.390000,-0.380000,-0.380000,-0.370000,...,0.570000,0.600000,0.640000,0.680000,0.720000,0.720000,0.770000,0.810000,0.860000,Lobith
1005.000,-0.390000,-0.390000,-0.390000,-0.390000,-0.400000,-0.390000,-0.390000,-0.390000,-0.380000,-0.370000,...,0.480000,0.510000,0.550000,0.590000,0.630000,0.610000,0.650000,0.700000,0.750000,Lobith
1006.000,-0.394500,-0.394500,-0.394500,-0.394500,-0.402941,-0.396712,-0.395783,-0.389555,-0.383326,-0.377097,...,0.286773,0.322287,0.359276,0.397779,0.437836,0.365588,0.408875,0.453837,0.500514,Lobith

In [6]:
# read kilometermarkering
kmm_df= gpd.read_file(kmmarkering, crs=28992)

# read vaarwegvakken
vwv_df = gpd.read_file(vaarwegvakken, crs=28992)

print(vwv_df.crs)

vwv = {}
kmm = {}
waterdepth = {}

# Dict with vaarwegvakken per River
for key, value in sheet_names.items():
    # Select vaarwegvakken for River
    vwv[key] = vwv_df.loc[vwv_df["vrt_naam"].str.contains(value, case=False)]
    # Select kilometermarkeringen
    kmm[key] = kmm_df.loc[kmm_df["vwk_id"].isin(vwv[key]["vwk_id"])]
    # Merge kilometermarkering with waterdepth data
    waterdepth[key] = df[key].merge(kmm[key], how="left", left_index=True, right_index=False, right_on="gtlwaarde" ).set_index('gtlwaarde')
    
ws = pd.concat([waterdepth["Bovenrijn-Waal"], waterdepth["Pkan-NRijn-Lek"], waterdepth["IJssel"]])


# Maas

vwv_maas = vwv_df.loc[vwv_df["vrt_naam"].str.contains("Maas", case=False)]
kmm_maas = kmm_df.loc[kmm_df["vwk_id"].isin(vwv_maas["vwk_id"])]
ws_maas = df_maas.merge(kmm_maas, how="left", left_index=True, right_index=False, right_on="gtlwaarde" ).set_index('gtlwaarde')
ws_maas.loc[~ws_maas['geometry'].isnull()]

epsg:28992

,80,155,280,530,1030,1280,1500,1982,2308,2609,...,4396,reference_location,id,vwk_id,vwk_begindatum,pos_tov_as,ltrwaarde,afstand,mst_code,geometry
gtlwaarde,,,,,,,,,,,,,,,,,,,,,
3,44.17,44.28,44.54,45.19,46.37,46.94,47.44,48.54,49.21,49.73,...,51.71,St. Pieter,kmmarkeringen.689,2595.0,2003-04-30,R,None,349.0,O,POINT (177976.936 322567.643)
3,44.17,44.28,44.54,45.19,46.37,46.94,47.44,48.54,49.21,49.73,...,51.71,St. Pieter,kmmarkeringen.1280,2776.0,2019-05-31,R,None,1253.0,O,POINT (186554.429 421332.175)
3,44.17,44.28,44.54,45.19,46.37,46.94,47.44,48.54,49.21,49.73,...,51.71,St. Pieter,kmmarkeringen.2304,3784.0,2020-10-31,R,None,2431.0,O,POINT (192968.185 355638.677)
4,44.17,44.27,44.48,45.03,46.09,46.59,47.01,48.03,48.65,49.13,...,50.96,St. Pieter,kmmarkeringen.553,2776.0,2019-05-31,R,None,2360.0,O,POINT (186014.129 422296.073)
4,44.17,44.27,44.48,45.03,46.09,46.59,47.01,48.03,48.65,49.13,...,50.96,St. Pieter,kmmarkeringen.690,2595.0,2003-04-30,R,None,1350.0,O,POINT (178417.783 323466.647)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245,0.36,0.44,0.56,0.86,1.17,1.24,1.32,1.61,1.88,2.17,...,3.64,St. Pieter,kmmarkeringen.1734,5551.0,2018-10-31,R,None,1522.0,B,POINT (130067.519 423977.626)
246,0.36,0.43,0.56,0.85,1.16,1.22,1.29,1.55,1.80,2.07,...,3.51,St. Pieter,kmmarkeringen.142,2723.0,2003-04-30,R,None,9775.0,B,POINT (122454.380 414647.799)
246,0.36,0.43,0.56,0.85,1.16,1.22,1.29,1.55,1.80,2.07,...,3.51,St. Pieter,kmmarkeringen.1733,5551.0,2018-10-31,R,None,2481.0,B,POINT (129299.576 424539.580)
247,0.36,0.43,0.55,0.84,1.14,1.20,1.25,1.48,1.71,1.96,...,3.31,St. Pieter,kmmarkeringen.120,2723.0,2003-04-30,R,None,10801.0,B,POINT (121433.389 414564.234)
247,0.36,0.43,0.55,0.84,1.14,1.20,1.25,1.48,1.71,1.96,...,3.31,St. Pieter,kmmarkeringen.1732,5551.0,2018-10-31,R,None,3448.0,B,POINT (128986.583 425417.146)

In [7]:
# Not all records have a geometry. Remove all data without geometry
# This is data between kilometermarkeringen and some points in germany
ws = ws.loc[~ws['geometry'].isnull()]
ws_maas = ws_maas.loc[~ws_maas['geometry'].isnull()]
ws

,703.3,738.98,774.78,810.84,847.19,883.69,919.63,958.35,999.8,1040.45,...,16140.64,reference_location,id,vwk_id,vwk_begindatum,pos_tov_as,ltrwaarde,afstand,mst_code,geometry
gtlwaarde,,,,,,,,,,,,,,,,,,,,,
858.0,7.04,7.13,7.22,7.31,7.40,7.49,7.62,7.71,7.81,7.91,...,18.86,Lobith,kmmarkeringen.1873,5641.0,2019-10-31,R,None,245.0,B,POINT (208483.685 428425.162)
859.0,6.90,6.99,7.08,7.18,7.27,7.37,7.49,7.59,7.68,7.78,...,18.71,Lobith,kmmarkeringen.1874,5641.0,2019-10-31,R,None,1218.0,B,POINT (207577.070 428777.472)
860.0,6.76,6.86,6.95,7.04,7.14,7.24,7.36,7.46,7.56,7.66,...,18.58,Lobith,kmmarkeringen.1875,5641.0,2019-10-31,R,None,2181.0,B,POINT (206648.079 429027.343)
861.0,6.63,6.73,6.82,6.92,7.02,7.12,7.23,7.33,7.43,7.53,...,18.38,Lobith,kmmarkeringen.1876,5641.0,2019-10-31,R,None,3193.0,B,POINT (205639.535 429074.712)
862.0,6.52,6.62,6.72,6.82,6.92,7.02,7.13,7.23,7.33,7.43,...,17.98,Lobith,kmmarkeringen.1877,5641.0,2019-10-31,R,None,4199.0,B,POINT (204636.708 429104.943)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1001.0,-0.39,-0.39,-0.39,-0.39,-0.40,-0.39,-0.38,-0.38,-0.37,-0.37,...,1.17,Lobith,kmmarkeringen.1260,4551.0,2012-12-31,R,None,1255.0,P,POINT (186370.638 510558.876)
1002.0,-0.39,-0.39,-0.39,-0.39,-0.40,-0.39,-0.39,-0.38,-0.37,-0.37,...,1.07,Lobith,kmmarkeringen.898,1412.0,2012-12-31,R,None,446.0,P,POINT (185552.685 510632.630)
1003.0,-0.39,-0.39,-0.39,-0.39,-0.40,-0.39,-0.39,-0.38,-0.37,-0.37,...,0.99,Lobith,kmmarkeringen.1169,1413.0,2012-12-31,R,None,923.0,P,POINT (184456.920 510711.802)
1004.0,-0.39,-0.39,-0.39,-0.39,-0.40,-0.39,-0.39,-0.38,-0.38,-0.37,...,0.86,Lobith,kmmarkeringen.899,1413.0,2012-12-31,R,None,1919.0,P,POINT (183461.379 510741.195)
1005.0,-0.39,-0.39,-0.39,-0.39,-0.40,-0.39,-0.39,-0.39,-0.38,-0.37,...,0.75,Lobith,kmmarkeringen.1170,1413.0,2012-12-31,R,None,2903.0,P,POINT (182477.586 510735.885)

In [8]:
# Transform geometry


ws = gpd.GeoDataFrame(ws, crs=28992, geometry="geometry")
ws_maas = gpd.GeoDataFrame(ws_maas, crs=28992, geometry="geometry")

# correct crs
ws = ws.to_crs(4326)
ws_maas = ws_maas.to_crs(4326)

ws

,703.3,738.98,774.78,810.84,847.19,883.69,919.63,958.35,999.8,1040.45,...,16140.64,reference_location,id,vwk_id,vwk_begindatum,pos_tov_as,ltrwaarde,afstand,mst_code,geometry
gtlwaarde,,,,,,,,,,,,,,,,,,,,,
858.0,7.04,7.13,7.22,7.31,7.40,7.49,7.62,7.71,7.81,7.91,...,18.86,Lobith,kmmarkeringen.1873,5641.0,2019-10-31,R,None,245.0,B,POINT (6.16330 51.84184)
859.0,6.90,6.99,7.08,7.18,7.27,7.37,7.49,7.59,7.68,7.78,...,18.71,Lobith,kmmarkeringen.1874,5641.0,2019-10-31,R,None,1218.0,B,POINT (6.15020 51.84509)
860.0,6.76,6.86,6.95,7.04,7.14,7.24,7.36,7.46,7.56,7.66,...,18.58,Lobith,kmmarkeringen.1875,5641.0,2019-10-31,R,None,2181.0,B,POINT (6.13676 51.84743)
861.0,6.63,6.73,6.82,6.92,7.02,7.12,7.23,7.33,7.43,7.53,...,18.38,Lobith,kmmarkeringen.1876,5641.0,2019-10-31,R,None,3193.0,B,POINT (6.12213 51.84795)
862.0,6.52,6.62,6.72,6.82,6.92,7.02,7.13,7.23,7.33,7.43,...,17.98,Lobith,kmmarkeringen.1877,5641.0,2019-10-31,R,None,4199.0,B,POINT (6.10758 51.84831)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1001.0,-0.39,-0.39,-0.39,-0.39,-0.40,-0.39,-0.38,-0.38,-0.37,-0.37,...,1.17,Lobith,kmmarkeringen.1260,4551.0,2012-12-31,R,None,1255.0,P,POINT (5.85004 52.58171)
1002.0,-0.39,-0.39,-0.39,-0.39,-0.40,-0.39,-0.39,-0.38,-0.37,-0.37,...,1.07,Lobith,kmmarkeringen.898,1412.0,2012-12-31,R,None,446.0,P,POINT (5.83798 52.58242)
1003.0,-0.39,-0.39,-0.39,-0.39,-0.40,-0.39,-0.39,-0.38,-0.37,-0.37,...,0.99,Lobith,kmmarkeringen.1169,1413.0,2012-12-31,R,None,923.0,P,POINT (5.82182 52.58319)
1004.0,-0.39,-0.39,-0.39,-0.39,-0.40,-0.39,-0.39,-0.38,-0.38,-0.37,...,0.86,Lobith,kmmarkeringen.899,1413.0,2012-12-31,R,None,1919.0,P,POINT (5.80714 52.58351)
1005.0,-0.39,-0.39,-0.39,-0.39,-0.40,-0.39,-0.39,-0.39,-0.38,-0.37,...,0.75,Lobith,kmmarkeringen.1170,1413.0,2012-12-31,R,None,2903.0,P,POINT (5.79262 52.58351)

In [9]:
# Pivot dataframe to easily lookup the waterdepth as function of the discharge at Lobith

values = []
ids = []

for col in ws.columns:
    if type(col) is float:
        values.append(col)
    else:
        ids.append(col)
        
ws = ws.melt(id_vars=ids, value_vars=values).rename(columns={"variable": "discharge", "value": "ws"})

values = []
ids = []

for col in ws_maas.columns:
    if type(col) is int:
        values.append(col)
    else:
        ids.append(col)
        
ws_maas = ws_maas.melt(id_vars=ids, value_vars=values).rename(columns={"variable": "discharge", "value": "ws"})

In [10]:
ws = pd.concat([ws, ws_maas])

In [11]:
ws.to_file("ws.geojson", driver='GeoJSON')